「資料科學家的 pandas 實戰手冊：掌握 40 個實用數據技巧」
參考網址: https://ppt.cc/ffxPxx

**0. 套件匯入**

In [1]:
import pandas 
pandas.__version__ # 1.0.3

'1.0.3'

**1. 建立DataFrame(使用Dict)**

In [0]:
import pandas 

dic = {
    "col 1" : [1, 2, 3],
    "col 2" : [10, 20, 30],
    "col 3" : list('xyz'),
    "col 4" : ['a','b','c'],
    "col 5" : pandas.Series(range(3))
}

df = pandas.DataFrame(dic)
df

   col 1  col 2 col 3 col 4  col 5
0      1     10     x     a      0
1      2     20     y     b      1
2      3     30     z     c      2

**2.確認屬性**

In [0]:
import pandas 

dic = {
    "col 1" : [1, 2, 3],
    "col 2" : [10, 20, 30],
    "col 3" : list('xyz'),
    "col 4" : ['a','b','c'],
    "col 5" : pandas.Series(range(3))
}

df = pandas.DataFrame(dic)
df
# ndim
print(df.ndim)  # 確認維度
# shape
print(df.shape) # 確認shape
# dtypes
print(df.dtypes) # 確認Data Type

2
(3, 5)
col 1     int64
col 2     int64
col 3    object
col 4    object
col 5     int64
dtype: object

**3_1.更改DF欄位名稱** (使用rename())

In [0]:
import pandas

dic = {
    "col 1" : [1, 2, 3],
    "col 2" : [10, 20, 30],
    "col 3" : list('abc'),
    "col 4" : ['a','b','c'],
    "col 5" : pandas.Series(range(3))
}

df = pandas.DataFrame(dic)

# 更改動作，使用reanme()
rename_dic = {"col 1" : 'x', 'col 2': '10x'}

df = df.rename(rename_dic, axis=1) # 在 pandas 裡大部分函式預設處理的軸為列（row）：以 axis=0 表示；而將 axis 設置為 1 則代表你想以行（column）為單位套用該函式。

df

   x  10x col 3 col 4  col 5
0  1   10     a     a      0
1  2   20     b     b      1
2  3   30     c     c      2

**3_2.更改DF欄位名稱** (使用column())

In [0]:
import pandas

dic = {
    "col 1" : [1, 2, 3],
    "col 2" : [10, 20, 30],
    "col 3" : list('abc'),
    "col 4" : ['a','b','c'],
    "col 5" : pandas.Series(range(3))
}

df = pandas.DataFrame(dic)

# 進行更改動作，使用column()
df.columns = ['x','10x'] + list(df.columns[2:])
#df.columns = ['x3','x4','x5'] + list(df.columns[3:])

df 
#print(df)

   x  10x col 3 col 4  col 5
0  1   10     a     a      0
1  2   20     b     b      1
2  3   30     c     c      2

**4_1.隨機建立 DataFrame**

In [0]:
import pandas

# 使用pandas.util.testing
pandas.util.testing.makeDataFrame().head(10) # .head()顯示DataFrame中的前n筆
#pandas.util.testing.makeDataFrame().head(5) # .tail()則顯示DataFrame中的後n筆

/usr/local/lib/python3.6/dist-packages/pandas/util/__init__.py:23: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing

                   A         B         C         D
FOOSwSzJ1z  1.055424 -0.097722  0.123237 -1.241594
HgW59uSkFA  0.933481 -2.532075  1.140173  0.129518
LazJTLgasj  1.067143  1.829266  2.942387  0.066641
BcaWWl9f41  0.136471  0.587425  0.559309 -0.973614
KnUdcTNc0u  0.184710 -1.392931 -0.598682 -0.170522
hyl5LyOscj  1.629932  0.115097  0.977559 -0.555326
KJLztDSFNQ  1.351728 -0.054810  1.082044 -1.537678
MsKReSGtez -1.578206 -1.157235 -0.605539  0.521009
Uf4EuyqLc9 -1.393740 -1.118801 -0.716206 -0.817222
uThJUg7p8w -0.055199 -0.836333 -1.170199  1.320805

**4_2.隨機建立 DataFrame**(混和)

In [0]:
import pandas

# 使用pandas.util.testing.makeMixedDataFrame()
pandas.util.testing.makeMixedDataFrame()

     A    B     C          D
0  0.0  0.0  foo1 2009-01-01
1  1.0  1.0  foo2 2009-01-02
2  2.0  0.0  foo3 2009-01-05
3  3.0  1.0  foo4 2009-01-06
4  4.0  0.0  foo5 2009-01-07

**!Error 5. 將複製內容(Excel,Google Sheet)傳進DataFrame**

In [0]:
import pandas

df = pandas.read_clipboard()
df

PyperclipException: ignored

**6.讀取csv檔案**

In [0]:
import pandas

df = pandas.read_csv("http://bit.ly/kaggletrain")
df

     PassengerId  Survived  Pclass  ...     Fare Cabin  Embarked
0              1         0       3  ...   7.2500   NaN         S
1              2         1       1  ...  71.2833   C85         C
2              3         1       3  ...   7.9250   NaN         S
3              4         1       1  ...  53.1000  C123         S
4              5         0       3  ...   8.0500   NaN         S
..           ...       ...     ...  ...      ...   ...       ...
886          887         0       2  ...  13.0000   NaN         S
887          888         1       1  ...  30.0000   B42         S
888          889         0       3  ...  23.4500   NaN         S
889          890         1       1  ...  30.0000  C148         C
890          891         0       3  ...   7.7500   NaN         Q

[891 rows x 12 columns]

**Trying 7. 試作實例:臺中市政府警察局109年2月份交通事故資料**

In [0]:
# 參考網址: https://opendata.taichung.gov.tw/dataset/e23f0ed1-5d12-4b79-9c0e-adf18c5a3c10/resource/eba67a1b-0e65-4247-bd56-bb2f6f296f7e
# 資料網址: https://datacenter.taichung.gov.tw/swagger/OpenData/563c7681-df3c-4159-84c1-e587373742d5
import pandas, csv, requests
from bs4 import BeautifulSoup

**8. 查看DF記憶體使用量**

In [0]:
import pandas

df.info(memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 322.0 KB

**9.Series物件**

是一個有標籤的1維陣列

In [0]:
import pandas

s = pa.Series([12, 29, 72, 4, 8, 101])
print(s)

0     12
1     29
2     72
3      4
4      8
5    101
dtype: int64

**10_1.建立自訂索引的Series物件**

In [0]:
import pandas

fruits = ["蘋果", "橘子", "梨子", "櫻桃"]
quantities = [15, 33, 45, 55]

s = pandas.Series(quantities, index = fruits)
print(s)
#print(s.index)
#print(s.values)

蘋果    15
橘子    33
梨子    45
櫻桃    55
dtype: int64

**10_2.建立自訂索引的Series物件, 其他操作**

In [0]:
import pandas

fruits = ["蘋果", "橘子", "梨子", "櫻桃"]
quantities = [15, 33, 45, 55]

s = pandas.Series(quantities, index = fruits)
# 指定index,取出資料
print("橘子= ",s["橘子"])
print()
# 指定多個index,取出多個資料,使用兩個[]
print(s[["橘子","梨子","櫻桃"]])
print()
# Series可執行運算
s = (s + 2) * 3
print(s)

橘子=  33

橘子    33
梨子    45
櫻桃    55
dtype: int64

蘋果     51
橘子    105
梨子    141
櫻桃    171
dtype: int64

**11.使用dict建立DF**

In [0]:
import pandas

products = {"分類":["居家","居家","娛樂","娛樂","科技","科技"],
            "商店":["家樂福","大潤發","家樂福","全聯超商","大潤發","家樂福"],
            "價格":[11.42, 23.50, 19.99, 15.95, 55.75, 111.55]}

df = pandas.DataFrame(products)
print(df)

html = df.to_html("Ch12_2_1.html")

   分類    商店      價格
0  居家   家樂福   11.42
1  居家   大潤發   23.50
2  娛樂   家樂福   19.99
3  娛樂  全聯超商   15.95
4  科技   大潤發   55.75
5  科技   家樂福  111.55

**12_1. 建立自訂索引的DF物件**

In [0]:
import pandas

products = {"分類":["居家","居家","娛樂","娛樂","科技","科技"],
            "商店":["家樂福","大潤發","家樂福","全聯超商","大潤發","家樂福"],
            "價格":[11.42, 23.50, 19.99, 15.95, 55.75, 111.55]}

ordinals = ["A","B","C","D","E","F"]

df = pandas.DataFrame(products, index = ordinals)
print(df)

   分類    商店      價格
A  居家   家樂福   11.42
B  居家   大潤發   23.50
C  娛樂   家樂福   19.99
D  娛樂  全聯超商   15.95
E  科技   大潤發   55.75
F  科技   家樂福  111.55

**12_1. 建立自訂索引的DF物件, 其他操作**

In [0]:
import pandas

products = {"分類":["居家","居家","娛樂","娛樂","科技","科技"],
            "商店":["家樂福","大潤發","家樂福","全聯超商","大潤發","家樂福"],
            "價格":[11.42, 23.50, 19.99, 15.95, 55.75, 111.55]}

ordinals = ["A","B","C","D","E","F"]

df = pandas.DataFrame(products, index = ordinals)
print(df)
print()
print("***不同的改變index的方式***")
df2 = pandas.DataFrame(products)
df2.index = ordinals
print(df)
print()
print("***重新指定DF的欄位順序***")
df = pandas.DataFrame(products, columns = ["價格","分類","商店"], index = ordinals)
print(df)
print()
print("***使用存在的column做為index***")
df = pandas.DataFrame(products, columns = ["商店","價格"], index = products["分類"])
print(df)
print()
print("***轉置***")
print(df.T)

   分類    商店      價格
A  居家   家樂福   11.42
B  居家   大潤發   23.50
C  娛樂   家樂福   19.99
D  娛樂  全聯超商   15.95
E  科技   大潤發   55.75
F  科技   家樂福  111.55

***不同的改變index的方式***
   分類    商店      價格
A  居家   家樂福   11.42
B  居家   大潤發   23.50
C  娛樂   家樂福   19.99
D  娛樂  全聯超商   15.95
E  科技   大潤發   55.75
F  科技   家樂福  111.55

***重新指定DF的欄位順序***
       價格  分類    商店
A   11.42  居家   家樂福
B   23.50  居家   大潤發
C   19.99  娛樂   家樂福
D   15.95  娛樂  全聯超商
E   55.75  科技   大潤發
F  111.55  科技   家樂福

***使用存在的column做為index***
      商店      價格
居家   家樂福   11.42
居家   大潤發   23.50
娛樂   家樂福   19.99
娛樂  全聯超商   15.95
科技   大潤發   55.75
科技   家樂福  111.55

***轉置***
       居家    居家     娛樂     娛樂     科技      科技
商店    家樂福   大潤發    家樂福   全聯超商    大潤發     家樂福
價格  11.42  23.5  19.99  15.95  55.75  111.55

**13. 匯出DF至檔案**

In [0]:
import pandas

products = {"分類":["居家","居家","娛樂","娛樂","科技","科技"],
            "商店":["家樂福","大潤發","家樂福","全聯超商","大潤發","家樂福"],
            "價格":[11.42, 23.50, 19.99, 15.95, 55.75, 111.55]}

df = pandas.DataFrame(products, columns = ["分類","商店","價格"])

df.to_csv("products.csv", index = False, encoding = "utf8")
#df.to_json("products.json")
#df.to_html("products.html")
#df.to_excel("products.excel")
#df.to_sql("products","products.sql") 第一個是資料表,第二個是資料庫

**14.讀取檔案轉換至DF**

In [0]:
import pandas

df = pandas.read_csv("products.csv", encoding = "utf8")
print(df)
#df.read_json("products.json")
#df.read_html("products.html")
#df.read_excel("products.excel")
#df.read_sql("products","products.sql") 第一個是資料表,第二個是資料庫

# 將csv的第一個column轉為index並讀取, index_col = n
df = pandas.read_csv("products.csv", index_col = 0, encoding = "utf8")

**15. 讀取Sql至DF**

In [0]:
import pandas
import sqlite3

db = sqlite3.connect("localhost", "root", "", "mybooks", charset = "utf8")
sql = "Select * From books"

df = pd.read_sql(sql, db)

print(df.head())

db.close()

**16.DF的其他操作**

In [0]:
import pandas

products = {"分類":["居家","居家","娛樂","娛樂","科技","科技"],
            "商店":["家樂福","大潤發","家樂福","全聯超商","大潤發","家樂福"],
            "價格":[11.42, 23.50, 19.99, 15.95, 55.75, 111.55]}

df = pandas.DataFrame(products)
print(df)
print()
print("***顯示前幾筆record***")
print(df.head(3))
print()
print("***顯示後幾筆record***")
print(df.tail(3))
print()
print("***顯示自訂欄位標籤***")
df.colums = ["type","name","price"]
print(df.head(3))
print()
print("***顯示DF的index, column, data***")
print(df.index)
print(df.columns)
print(df.values)
print()
print("***顯示DF的shape, info***")
print(df.shape)
print(df.info)

   分類    商店      價格
0  居家   家樂福   11.42
1  居家   大潤發   23.50
2  娛樂   家樂福   19.99
3  娛樂  全聯超商   15.95
4  科技   大潤發   55.75
5  科技   家樂福  111.55

***顯示前幾筆record***
   分類   商店     價格
0  居家  家樂福  11.42
1  居家  大潤發  23.50
2  娛樂  家樂福  19.99

***顯示後幾筆record***
   分類    商店      價格
3  娛樂  全聯超商   15.95
4  科技   大潤發   55.75
5  科技   家樂福  111.55

***顯示自訂欄位標籤***
   分類   商店     價格
0  居家  家樂福  11.42
1  居家  大潤發  23.50
2  娛樂  家樂福  19.99

***顯示DF的index, column, data***
RangeIndex(start=0, stop=6, step=1)
Index(['分類', '商店', '價格'], dtype='object')
[['居家' '家樂福' 11.42]
 ['居家' '大潤發' 23.5]
 ['娛樂' '家樂福' 19.99]
 ['娛樂' '全聯超商' 15.95]
 ['科技' '大潤發' 55.75]
 ['科技' '家樂福' 111.55]]

***顯示DF的shape, info***
(6, 3)
<bound method DataFrame.info of    分類    商店      價格
0  居家   家樂福   11.42
1  居家   大潤發   23.50
2  娛樂   家樂福   19.99
3  娛樂  全聯超商   15.95
4  科技   大潤發   55.75
5  科技   家樂福  111.55>

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:17: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access

**17.使用iterrows走訪DF**

In [0]:
import pandas

products = {"分類":["居家","居家","娛樂","娛樂","科技","科技"],
            "商店":["家樂福","大潤發","家樂福","全聯超商","大潤發","家樂福"],
            "價格":[11.42, 23.50, 19.99, 15.95, 55.75, 111.55]}

df = pandas.DataFrame(products)

for index, row in df.iterrows():
  print(index, row["分類"], row["商店"], row["價格"])

0 居家 家樂福 11.42
1 居家 大潤發 23.5
2 娛樂 家樂福 19.99
3 娛樂 全聯超商 15.95
4 科技 大潤發 55.75
5 科技 家樂福 111.55

**18.指定DF的index**

In [0]:
import pandas

products = {"分類":["居家","居家","娛樂","娛樂","科技","科技"],
            "商店":["家樂福","大潤發","家樂福","全聯超商","大潤發","家樂福"],
            "價格":[11.42, 23.50, 19.99, 15.95, 55.75, 111.55]}

df = pandas.DataFrame(products)

df2 = df.set_index("分類")
print(df2.head())
print()

df3 = df2.reset_index()
print(df3.head())

      商店     價格
分類
居家   家樂福  11.42
居家   大潤發  23.50
娛樂   家樂福  19.99
娛樂  全聯超商  15.95
科技   大潤發  55.75

   分類    商店     價格
0  居家   家樂福  11.42
1  居家   大潤發  23.50
2  娛樂   家樂福  19.99
3  娛樂  全聯超商  15.95
4  科技   大潤發  55.75

**19.指定DF的多個column複合index**

In [0]:
import pandas

products = {"分類":["居家","居家","娛樂","娛樂","科技","科技"],
            "商店":["家樂福","大潤發","家樂福","全聯超商","大潤發","家樂福"],
            "價格":[11.42, 23.50, 19.99, 15.95, 55.75, 111.55]}

df = pandas.DataFrame(products)

df2 = df.set_index(["分類"],["商店"])
df2.sort_index(ascending= False, inplace = True)
print(df2)

      商店      價格
分類
科技   大潤發   55.75
科技   家樂福  111.55
居家   家樂福   11.42
居家   大潤發   23.50
娛樂   家樂福   19.99
娛樂  全聯超商   15.95